#!/bin/bash

L=$(echo -e 'en.us\npt.br' | dmenu -p "layout: " -fn "Monoid-9" -nb "#1D2021" -nf "#D8CBA5" -sb "#AF3A03" -sf "#EBDBB2")

case $L in
    en.us)
        setxkbmap -layout us
    ;;
    pt.br)
        setxkbmap -layout br -model thinkpad
    ;;
esac
